# Generated by Django 3.1.1 on 2020-09-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_mark',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_rare',
            new_name='rare',
        ),
    ]
